### ISSUE TITLE
希望为这个有趣的项目提供中文翻译

### ISSUE THREAD

**Issue by Yorha4D** [googincheng/ComfyUX#12]
HI~朋友
我是AIGODLIKE开发小组的成员，最近我看到这个极具创意的项目，它在一定程度改善了节点的可读性。
进入正题，我看到其中有中英翻译的功能，但对于很多自定义节点支持的不是很全。所以不知是否可以和我们的开源翻译项目兼容或直接读取它，从而使您的项目语言完整性得到大幅提高
https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION/
无论如何，希望对你有用

**Comment by Yorha4D** [comment]
@googincheng

**Comment by googincheng** [comment]
没问题的，非常感谢，AIGODLIKE-ComfyUI-Translation也是帮助了很多中文社区的人使用ComfyUI

**Comment by Yorha4D** [comment]
OK,有需要随时联系
