### ISSUE TITLE
我发现了另一个有意思的节点，聊聊我的想法

### ISSUE THREAD

**Issue by water110** [googincheng/ComfyUX#13]
节点地址：https://github.com/Nuked88/ComfyUI-N-Sidebar
这个节点中也有关于节点搜索和预览的功能，然后主体功能也是用侧边栏的形式展示的，他这个可以对节点自定义分类，因为很多插件中包含了N多个节点，但是我们经常用的节点只是其中一部分，自定义分类的功能可以帮我们把经常用到的节点过滤出来和按不同功能进行归类。我同时希望有一个给节点自定义别名的功能，这样可以更方便记忆，这个目前还未实现。
特别值得一说的是，这个插件中有保存模板的功能，这样可以把一些功能流程节点（比如遮罩处理，高清修复等）固化下来，也可以理解为模块化，这样后续复用非常方便。
目前有不少插件的展现形式是侧边栏的方式，这样会导致整个界面充满了侧边栏，看起来很拥挤，也容易有样式冲突，希望大家可以借鉴下彼此的设计思想，让插件的能力越来越强、兼容性越来越好，让comfyUI使用效率越来越高，生态越来越繁荣。最后十分感谢作者提供的插件！

**Comment by googincheng** [comment]
在新的ComfyUI架构下，会有统一插件侧边栏管理，可以查看：https://github.com/Comfy-Org/ComfyUI_frontend
另外，如果希望在frontend版本下使用ComfyUX，可以查看此仓库：https://github.com/googincheng/ComfyUX-frontend-release
