### ISSUE TITLE
功能问题反馈

### ISSUE THREAD

**Issue by water110** [googincheng/ComfyUX#14]
![image](https://github.com/user-attachments/assets/28cd91d1-f87c-4d92-b42f-b230ff4a13ce)
![image](https://github.com/user-attachments/assets/a959d234-f786-4fe9-aa38-e50e28140382)
![image](https://github.com/user-attachments/assets/a802181b-2122-4d2a-b178-c069297b1308)
![image](https://github.com/user-attachments/assets/35878d76-90b2-4fef-9812-3d2dd6be601f)
![image](https://github.com/user-attachments/assets/61ce526a-7e31-4cb5-a132-248e8d6ea524)
关于右上角的四个功能，可以详细说下吗，感觉有些乱：
首先在中文或者英文时，这几个按钮都存在中英文混着显示的问题，而不是纯英文或者纯中文展示；
1、**当没有执行任何队列时**，界面上显示的按钮分别为：运行（Run）、下一个运行（Queue Front）、自动（Auto）、批处理；
- **下一个运行（Queue Front）**：这里的中英文翻译有歧义，应该是【执行队列】吧
- **批处理（Batch）**：这里英文没翻译出来；

2、**当正在执行队列时**，界面上显示的按钮分别为：Add to Run Queue、下一个运行（Queue Front）、自动（Auto）、批处理；
- **Add to Run Queue**：这里中文没翻译出来，应该是【添加到队列】吧；

3、右侧工具栏中的【历史】和【节点】之间切换，点击【历史】TAB之后，没有任何反应，不知道为什么，我用的谷歌最新版浏览器。

4、装了这个插件之后，之前的在设置中有一个显示进度条的配置不再生效，即页面最上面不再显示当前队列执行的进度，这个是对于直观的查看当前队列的执行进度很有帮助的。

5、Crystool GPU监测这个模块可以自由拖拽位置不，目前如果要展示，固定在左上角，遮挡了其他工具的使用。

**Comment by googincheng** [comment]
1、翻译确实存在问题，正在解决。
2、历史tab没有任何反应，可否提供console log？以及comfyui版本？我这边是正常的
另外，目前建议等待8月15号[comfyui frontend](https://github.com/Comfy-Org/ComfyUI_frontend)合入Comfy UI主分支，如果希望在新的Frontend中使用ComfyUX，可[查看此仓库](https://github.com/googincheng/ComfyUX-frontend-release)
