### ISSUE TITLE
[feature request] independent plug-in for sidebar.

### ISSUE THREAD

**Issue by asshidhak** [googincheng/ComfyUX#2]
Hi @googincheng , 
cool feature, Could you plan a independent sidebar  plugin for comfyui ? 

![image](https://github.com/user-attachments/assets/28ded9de-8b18-4747-869d-860055a86923)

**Comment by googincheng** [comment]
Thks! Independent means? Float on viewport?

**Comment by asshidhak** [comment]
Hi @googincheng,
Sorry for unclear，I mean will you plan a version that only provide side bar feature?  
<img width="935" alt="image" src="https://github.com/user-attachments/assets/3e77e769-ede8-42de-ad13-9698f0470f06">

because in new comfyui webui, there's already a top-toolbar with same fuction as comfyUX. 
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/07afd8c6-8c7d-4a33-8c6c-7d8977568b2e">

**Comment by googincheng** [comment]
Got you. Not planning now, I think the ComfyUI topbar is great too, but personally speaking, I like ComfyUX more hhh. It make the whole UI style consistent

**Comment by asshidhak** [comment]
hi @googincheng , well, comfyUX is really an amazing plugins, hope  you could consider this request some day.   The split functional modules can be better integrated in ComfyUI. I believe this will be more suitable for most users. This will also make ComfyUX a more popular project , unless you don't mean to .

**Comment by googincheng** [comment]
Thks for your patience, I absolutely understand what you need, But I believe that only the consistency bring the great expereience. Let's said only provide the sidebar, I can't determine the height and width to make it best fit

**Comment by googincheng** [comment]
> hi @googincheng , well, comfyUX is really an amazing plugins, hope you could consider this request some day. The split functional modules can be better integrated in ComfyUI. I believe this will be more suitable for most users. This will also make ComfyUX a more popular project , unless you don't mean to .

Besides, The ComfyUI.org is now working on provide a new achitecture, which may help arrange the UI. Let's wait and see.
