### ISSUE TITLE
How to cancel a job ?

### ISSUE THREAD

**Issue by Mikerhinos** [googincheng/ComfyUX#6]
I'm using it since a couple of hours and I love it, I can have a global view of my workflow to follow the node advancement, while having big preview images, all the without having to move/zoom anything.

Though how do you cancel a running job ?

**Comment by googincheng** [comment]
Thanks for your like! I am working on it, seems ComfyUI not allow plugin to do this

**Comment by googincheng** [comment]
> I am working on it, seems ComfyUI not allow plugin to do this. If it can, you can cancel it at history tab

**Comment by googincheng** [comment]
[https://github.com/googincheng/ComfyUX/commit/0af06b546ccba0cbce9399cc915ea106b1977b55](Commit)

Fixed
